### ISSUE TITLE
Change some files

### ISSUE THREAD

**Issue by philipturner** [s4y/undot#2]

**Comment by s4y** [comment]
Hi @philipturner, sorry for the delay.

I'm not sure who this "we" is who's moved on, but I'm not part of it 🙂. I've used Swift on and off since it came out and I'm sure I'll use it more in the future, but I see a project's language choice as a preference, not a bug.

I might be more open to it once Xcode removes Objective-C from the New Project window or shows an alert if you select it:

<img width="373" alt="Menu showing a choice between Swift and Objective-C" src="https://user-images.githubusercontent.com/111870/148246143-d74df782-6277-460a-ab4a-46f68d921e92.png">

In any case, I added a license to the project and I'm totally open to a Swift fork.

**Comment by philipturner** [comment]
"We" refers to the general open-source community and I'm referring to the safety and approachability of Swift. I get that you're more familiar with Objective-C; I just have had an extremely negative experience with ObjC before and try to avoid it.
